services:
  postgres:
    image: bitnami/postgresql:14
    environment:
      POSTGRES_USER: subscription_user
      POSTGRES_PASSWORD: strongpassword
      POSTGRES_DB: subscription_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U subscription_user -d subscription_db" ]
      interval: 5s
      timeout: 5s
      retries: 5


  app:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/subscription_db
      SPRING_DATASOURCE_USERNAME: subscription_user
      SPRING_DATASOURCE_PASSWORD: strongpassword
      SPRING_JPA_HIBERNATE_DDL-AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network
    ports:
      - "8080:8080"
volumes:
  postgres_data:
networks:
  app-network: