services:
  postgres:
    image: bitnami/postgresql:14
    environment:
        POSTGRES_USER: subscription_user
        POSTGRES_PASSWORD: strongpassword
        POSTGRES_DB: subscription_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
        test: [ "CMD-SHELL", "pg_isready -U subscription_user -d subscription_db" ]
        interval: 5s
        timeout: 5s
        retries: 5


  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres
      DB_PORT: 5433:5432
      DB_NAME: subscription_db
      DB_USER: subscription_user
      DB_PASSWORD: strongpassword
    depends_on:
      postgres:
        condition: service_started

volumes:
  postgres_data: