spring:
  application:
    name: SubscriptionTestApp
  datasource:
    url: jdbc:postgresql://postgres:5432/subscription_db
    username: subscription_user
    password: strongpassword
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      format_sql: true