spring:
  application:
    name: SubscriptionTestApp
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL-AUTO}
    properties:
      hibernate:
      dialect: ${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT}
      format_sql: true
      show-sql: true